# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGr_QFB655P38Z2euobqxa1Flwo9dLil
"""

#include <iostream>

int main() {

    std::cout << "Dehqonov Biloliddin" << std::endl;

    return 0;
}

print("Dehqonov Biloliddin")